[package]
name = "anthropic-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anthropic = { git = "https://github.com/fdionisi/anthropic-sdk", rev = "ca40d11cb516498b7b96fbce6f22384625c62f30" }
anthropic_bedrock = { git = "https://github.com/fdionisi/anthropic-sdk", rev = "ca40d11cb516498b7b96fbce6f22384625c62f30" }
anthropic_vertexai = { git = "https://github.com/fdionisi/anthropic-sdk", rev = "ca40d11cb516498b7b96fbce6f22384625c62f30" }
anyhow = "1"
async-trait = "0.1.81"
aws-config = "1.5.5"
axum = "0.7"
axum-extra = { version = "0.9", features = ["typed-header"] }
clap = { version = "4.5.15", features = ["derive", "env"] }
futures = "0.3"
headers = "0.4"
reqwest = "0.12"
serde_json = "1"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.5.0", features = ["fs", "trace", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
